### ISSUE TITLE
Error 500 when opening Tasks-Manuscript Names

### ISSUE THREAD

**Issue by yroskov** [CatalogueOfLife/backend#937]
Leave FeedbackFrontend version: 2c59729 December 8, 2020 4:31 AMBackend version: 74a5865 December 10, 2020 3:59 AM

Working with World Plants in the clearinghouse, I tried to open Tasks - Manuscript Names report and got error message 500:

Request failed with status code 500
There was an error processing your request. It has been logged (ID 6a8283cbbe9807ea).
HTTP method: GET
https://api.catalogueoflife.org/dataset/3/decision/202222

![image](https://user-images.githubusercontent.com/28574252/102135512-b82f1880-3e1d-11eb-910e-66eb00c22b93.png)

**Comment by mdoering** [comment]
This was cause by a postgres problem:

```
org.apache.ibatis.exceptions.PersistenceException: 
### Error querying database.  Cause: org.postgresql.util.PSQLException: ERROR: out of shared memory
  Hint: You might need to increase max_locks_per_transaction.
### The error may exist in life/catalogue/db/mapper/DecisionMapper.xml
### The error may involve defaultParameterMap
### The error occurred while setting parameters
### SQL: SELECT       t.id IS NULL AS subject_broken,           ed.id AS id,     ed.dataset_key AS dataset_key,     ed.subject_dataset_key AS subject_dataset_key,     ed.original_subject_id AS original_subject_id,     ed.subject_id AS subject_id,     ed.subject_name AS subject_name,     ed.subject_authorship AS subject_authorship,     ed.subject_rank AS subject_rank,     ed.subject_code AS subject_code,     ed.subject_status AS subject_status,     ed.subject_parent AS subject_parent,     ed.note AS note,     ed.modified AS modified,     ed.modified_by AS modified_by,     ed.created AS created,     ed.created_by AS created_by,     ed.mode AS mode,     ed.name AS name,     ed.status AS status,     ed.extinct AS extinct,     ed.temporal_range_start AS temporal_range_start,     ed.temporal_range_end AS temporal_range_end,     ed.environments AS environments             FROM       decision ed       LEFT JOIN name_usage t ON t.dataset_key=ed.subject_dataset_key AND t.id=ed.subject_id             WHERE ed.id = ? AND ed.dataset_key=?
### Cause: org.postgresql.util.PSQLException: ERROR: out of shared memory
  Hint: You might need to increase max_locks_per_transaction.
```

Dodgy...
